version: '3.8'
services:
  mars-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=mars
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432